import React from 'react'
import { getGradeRoster, listTeachingAssignments, saveGrades } from '../api/apiClient'

const currentYear = `${new Date().getFullYear()}/${String((new Date().getFullYear() + 1) % 100).padStart(2, '0')}`
export default function TeacherGrades(){
  const [assignments,setAssignments]=React.useState([]); const [assignmentId,setAssignmentId]=React.useState(''); const [year,setYear]=React.useState(currentYear); const [quarter,setQuarter]=React.useState('1'); const [roster,setRoster]=React.useState([]); const [error,setError]=React.useState(''); const [loading,setLoading]=React.useState(false)
  React.useEffect(()=>{ listTeachingAssignments().then(data=>{setAssignments(data); if(data[0]) setAssignmentId(String(data[0].id))}).catch(e=>setError(e.message)) },[])
  React.useEffect(()=>{ if(!assignmentId) return; setLoading(true); getGradeRoster({assignmentId,academicYear:year,quarter}).then(data=>setRoster(data.students.map(s=>({...s,score:s.grade?.score ?? ''})))).catch(e=>setError(e.message)).finally(()=>setLoading(false)) },[assignmentId,year,quarter])
  const save=async()=>{ try { setError(''); await saveGrades({assignmentId,academicYear:year,quarter:Number(quarter),grades:roster.map(s=>({studentId:s.id,score:Number(s.score)}))}); alert('Quarter grades saved') } catch(e){setError(e.message)} }
  const chosen=assignments.find(a=>String(a.id)===assignmentId)
  return <div><div className="section-header"><div><span className="subtitle">Grades</span><h1 className="title">Enter quarterly grades</h1></div></div><div className="card section"><div className="form-row"><label className="input-label">Class and subject<select className="input-field" value={assignmentId} onChange={e=>setAssignmentId(e.target.value)}>{assignments.map(a=><option key={a.id} value={a.id}>{a.class.name} · {a.subject.name}</option>)}</select></label><label className="input-label">Academic year<input className="input-field" value={year} onChange={e=>setYear(e.target.value)} /></label><label className="input-label">Quarter<select className="input-field" value={quarter} onChange={e=>setQuarter(e.target.value)}>{[1,2,3,4].map(q=><option key={q}>{q}</option>)}</select></label></div>{chosen&&<p className="subtitle">{chosen.class.name} · {chosen.subject.name}</p>}</div>{error&&<div className="error">{error}</div>}{loading?<div className="loader">Loading grades…</div>:<div className="space-y-3">{roster.map((student,index)=><div className="student-card" key={student.id}><div className="card-body form-row"><div style={{flex:1}}><p className="student-name">{student.name}</p><p className="student-roll">Student {index+1}</p></div><label className="input-label">Score out of 100<input className="input-field" type="number" min="0" max="100" value={student.score} onChange={e=>setRoster(rows=>rows.map(row=>row.id===student.id?{...row,score:e.target.value}:row))} /></label></div></div>)}</div>}<div className="submit-panel"><button className="btn-primary" disabled={!roster.length} onClick={save}>Save grades</button></div></div>
}
