import type { Request, Response } from "express";
import * as grades from "../services/grade-service";
import { AppError } from "../lib/app-error";

function one(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] : value ?? ""; }
function fail(error: unknown, response: Response) { if (error instanceof AppError) { response.status(error.statusCode).json({ success: false, error: { message: error.message, code: error.code } }); return; } throw error; }
function user(request: Request, response: Response) { if (!request.user) { response.status(401).json({ success: false, error: { message: "Unauthorized", code: "UNAUTHORIZED" } }); return null; } return request.user; }
export async function createSubjectHandler(request: Request, response: Response) { try { const auth = user(request, response); if (!auth) return; response.status(201).json({ success: true, data: await grades.createSubject(auth.schoolId, request.body.name) }); } catch (error) { fail(error, response); } }
export async function listSubjectsHandler(request: Request, response: Response) { try { const auth = user(request, response); if (!auth) return; response.json({ success: true, data: await grades.listSubjects(auth.schoolId) }); } catch (error) { fail(error, response); } }
export async function createAssignmentHandler(request: Request, response: Response) { try { const auth = user(request, response); if (!auth) return; response.status(201).json({ success: true, data: await grades.createTeachingAssignment(auth.schoolId, request.body) }); } catch (error) { fail(error, response); } }
export async function mineHandler(request: Request, response: Response) { try { const auth = user(request, response); if (!auth) return; response.json({ success: true, data: await grades.teacherAssignments(auth.userId, auth.schoolId) }); } catch (error) { fail(error, response); } }
export async function rosterHandler(request: Request, response: Response) { try { const auth = user(request, response); if (!auth) return; response.json({ success: true, data: await grades.assignmentRoster(one(request.params.assignmentId), auth.userId, auth.schoolId, request.query.academicYear, request.query.quarter) }); } catch (error) { fail(error, response); } }
export async function saveHandler(request: Request, response: Response) { try { const auth = user(request, response); if (!auth) return; response.json({ success: true, data: await grades.saveAssignmentGrades(one(request.params.assignmentId), auth.userId, auth.schoolId, request.body) }); } catch (error) { fail(error, response); } }
export async function homeroomHandler(request: Request, response: Response) { try { const auth = user(request, response); if (!auth) return; response.json({ success: true, data: await grades.homeroomResults(one(request.params.classId), auth.userId, auth.schoolId, request.query.academicYear, request.query.quarter) }); } catch (error) { fail(error, response); } }
export async function parentHandler(request: Request, response: Response) { try { const auth = user(request, response); if (!auth) return; response.json({ success: true, data: await grades.parentGrades(auth.userId, auth.schoolId, request.query.studentId, request.query.academicYear, request.query.quarter) }); } catch (error) { fail(error, response); } }
